using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Text;
using System.Threading.Tasks;
using System.Xml.Serialization;

namespace Comics
{
    public class Comic : INotifyPropertyChanged
    {
        private readonly string title;
        private readonly string author;
        private readonly string category;
        private readonly string path;
        private string imagePath = null;
        private List<string> filePaths = new List<string>();

        public string UniqueIdentifier { get { return "[" + author + "]" + title; } }
        public string ImagePath { get { return Metadata.ThumbnailSource ?? imagePath; } }
        // The thumbnail and metadata files are not to be generated by the Comic class itself (for performance reasons)
        public string ThumbnailPath { get { return Path.Combine(Defaults.UserThumbnailsFolder, UniqueIdentifier + ".jpgthumbnail"); } }
        public string MetadataPath { get { return Path.Combine(Defaults.UserMetadataFolder, UniqueIdentifier + ".xmlmetadata"); } }
        public string ContainingPath { get { return path; } }
        public List<string> FilePaths { get { return filePaths; } }

        public int Random { get; set; }

        public Metadata Metadata { get; set; }

        public event PropertyChangedEventHandler PropertyChanged;
        private void NotifyPropertyChanged([CallerMemberName] String propertyName = "")
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
        }

        public Comic(string title, string author, string category, string path)
        {
            this.title = title;
            this.author = author;
            this.category = category;
            this.path = path;

            if (Directory.Exists(path))
                AddDirectory(new DirectoryInfo(path));
            else if (File.Exists(path))
                filePaths.Add(path);
            else
                throw new Exception("Invalid path given to comic");

            if (!LoadMetadata())
                Metadata = new Metadata();
        }

        public void AddDirectory(DirectoryInfo directory)
        {
            FileInfo[] files = directory.GetFiles("*.*");

            foreach (FileInfo file in files)
            {
                string suffix = Path.GetExtension(file.Name).ToLowerInvariant();
                if (Defaults.Profile.Extensions.Contains(suffix))
                    filePaths.Add(file.FullName);
                if (imagePath == null && Defaults.ImageExtensions.Contains(suffix))
                    imagePath = file.FullName;
            }
        }

        public void CreateThumbnail()
        {
            // We're supposed to account for display scaling here.
            // int width = Defaults.ThumbnailWidthForVisual(this);
            int width = Defaults.ThumbnailWidthForVisual(null);
            if (File.Exists(ImagePath) &&
                Thumbnails.CreateThumbnailFromImage(ImagePath, width, ThumbnailPath)) { }
            else if (Thumbnails.CanCreateThumbnailFromAudio(ImagePath) &&
                Thumbnails.CreateThumbnailFromAudio(ImagePath, width, ThumbnailPath)) { }
            else if (Thumbnails.CanCreateThumbnailFromVideo(ImagePath) &&
                Thumbnails.CreateThumbnailFromVideo(ImagePath, width, ThumbnailPath)) { }
            else if (Thumbnails.CanCreateThumbnailFromAudio(FilePaths.First()) &&
                Thumbnails.CreateThumbnailFromAudio(FilePaths.First(), width, ThumbnailPath)) { }
            else if (Thumbnails.CanCreateThumbnailFromVideo(FilePaths.First()) &&
                Thumbnails.CreateThumbnailFromVideo(FilePaths.First(), width, ThumbnailPath)) { }
            else
                return;
            NotifyPropertyChanged("ThumbnailPath");
        }

        public SortedString Title
        {
            get { return Metadata.Title ?? new SortedString(title); }
            set { Metadata.Title = value; SaveMetadata(); NotifyPropertyChanged("Title"); }
        }

        public SortedString Author
        {
            get { return Metadata.Author ?? new SortedString(author); }
            set { Metadata.Author = value; SaveMetadata(); NotifyPropertyChanged("Author"); }
        }

        public SortedString Category
        {
            get { return Metadata.Category ?? new SortedString(category); }
            set { Metadata.Category = value; SaveMetadata(); NotifyPropertyChanged("Category"); }
        }

        public bool Loved
        {
            get { return Metadata.Loved; }
            set { Metadata.Loved = value; SaveMetadata(); NotifyPropertyChanged("Loved"); }
        }

        public bool Disliked
        {
            get { return Metadata.Disliked; }
            set { Metadata.Disliked = value; SaveMetadata(); NotifyPropertyChanged("Disliked"); }
        }
        
        // Calls Process.Start on ThumbnailPath.
        // Maybe I will eventually code a viewer into this program, but I already have an image viewer.
        public void OpenWithDefaultApplication()
        {
            Process.Start(filePaths.First());
        }

        public void OpenContainingFolder()
        {
            Process.Start(path);
        }

        public bool MatchesSearchText(string searchText)
        {
            if (String.IsNullOrWhiteSpace(searchText))
                return true;

            searchText = searchText.ToLowerInvariant();
            return Title.Display.ToLowerInvariant().Contains(searchText) ||
                Title.Sort.ToLowerInvariant().Contains(searchText) ||
                Author.Display.ToLowerInvariant().Contains(searchText) ||
                Author.Sort.ToLowerInvariant().Contains(searchText);
        }

        public bool MatchesCategories(ISet<string> categories)
        {
            return categories.Count == 0 || categories.Contains(Category.Display);
        }

        public bool MatchesAuthors(ISet<string> authors)
        {
            return authors.Count == 0 || authors.Contains(Author.Display);
        }
        
        public static readonly List<string> SortPropertyNames = new List<string> { "Author", "Title", "Category", "Random" };
        public static readonly int RandomSortIndex = 3;
        public static List<string> SortDescriptionPropertyNamesForIndex(int index)
        {
            List<string> sortPropertyNames = new List<string>(SortPropertyNames);
            if (index > 0 && index < sortPropertyNames.Count)
            {
                string preferredProperty = sortPropertyNames[index];
                sortPropertyNames.RemoveAt(index);
                sortPropertyNames.Insert(0, preferredProperty);
            }
            return sortPropertyNames;
        }

        public void SaveMetadata()
        {
            XmlSerializer writer = new XmlSerializer(typeof(Metadata));
            string path = Path.Combine(Defaults.UserMetadataFolder, MetadataPath);
            string tempPath = path + ".tmp";

            using (FileStream tempFile = File.Create(tempPath))
                writer.Serialize(tempFile, Metadata);

            if (File.Exists(path))
                File.Delete(path);

            File.Move(tempPath, path);
        }

        public bool LoadMetadata()
        {
            Metadata profile;
            XmlSerializer reader = new XmlSerializer(typeof(Metadata));
            string path = Path.Combine(Defaults.UserMetadataFolder, MetadataPath);

            if (!File.Exists(path))
                return false;

            using (StreamReader file = new StreamReader(path))
                profile = (Metadata)reader.Deserialize(file);

            Metadata = profile;
            return true;
        }
    }

    public class Metadata
    {
        public SortedString Title { get; set; }
        public SortedString Author { get; set; }
        public SortedString Category { get; set; }
        public bool Loved { get; set; }
        public bool Disliked { get; set; }
        public string ThumbnailSource { get; set; }
    }

    public class SortedString : IComparable {
        public string Display { get; set; }
        public string Sort { get; set; }

        public SortedString() { }

        public SortedString(string display, string sort)
        {
            Display = display;
            Sort = sort;
        }

        public SortedString(string display) : this(display, display) { }

        public override string ToString()
        {
            return Display.ToString();
        }

        public override bool Equals(object obj)
        {
            if (obj is SortedString)
                return Sort.Equals(((SortedString)obj).Sort);

            return Sort.Equals(obj);
        }

        public override int GetHashCode()
        {
            return Sort.GetHashCode();
        }

        public int CompareTo(object other)
        {
            if (other is SortedString)
                return Sort.CompareTo(((SortedString)other).Sort);

            return Sort.CompareTo(other);
        }
    }
}
